name: Proxy Auto-Updater

on:
  schedule:
    - cron: "*/20 * * * *"  # Ejecuta cada 20 minutos
  workflow_dispatch:        # Permite ejecución manual

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    timeout-minutes: 10     # Evita jobs colgados
    concurrency: 
      group: proxy-update   # Previene ejecuciones paralelas
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Necesario para el historial de commits

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"      # Cachea dependencias para más velocidad

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Increase file descriptors (para listas grandes)
        run: ulimit -n 1024

      - name: Run Proxy Updater
        run: python fetch_proxies.py --output ./proxies --workers 200 --timeout 5
        env:
          LOG_LEVEL: "INFO"

      - name: Commit and Push Changes
        if: success()
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Proxy Updater Bot"
          author_email: "actions@github.com"
          message: "🔄 Auto-update proxies [skip ci]"
          add: "./proxies/*.txt"
          pull_strategy: "rebase"

      - name: Create timestamped tag (solo en ejecuciones manuales)
        if: github.event_name == 'workflow_dispatch'
        run: |
          TAG="proxies-$(date +'%Y%m%d-%H%M')"
          git tag $TAG
          git push origin $TAG

      - name: Notify on failure
  if: failure()
  uses: 8398a7/action-slack@v3
  with:
    status: failure
    fields: job,commit,repo,message
    author_name: "Proxy Updater"
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
