name: Actualizar Proxies

on:
  schedule:
    - cron: "*/20 * * * *"  # Cada 20 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script de proxies
        run: python fetch_proxies.py

      - name: Confirmar cambios
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add .
          git commit -m "🔄 Actualización automática de proxies [$(date +'%F %T')]" || echo "No hay cambios"
          git push
